extends: airbnb
env:
  es6: true
  browser: true
  commonjs: true
  jest: true
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  prefer-error-callback: 0
  react/jsx-filename-extension: 0
  max-len: ['error', 100]
